### ISSUE TITLE
Many errors after fresh install: [Vue warn]: Unknown custom element

### ISSUE THREAD

**Issue by EarthmanWeb** [DivanteLtd/vsf-capybara#464]
## Current behavior

Thank you for all your work on this theme - I am running on the develop branch with a new installation of the theme, I have followed all the steps in the documentation, and yet I receive many of the following errors in the frontend, and it doesn't load correctly:

```
**[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. 
This is likely caused by incorrect HTML markup, for example nesting block-level elements inside 
<p>, or missing <tbody>. Bailing hydration and performing full client-side render.**

warn @ vue.runtime.esm.js:619
patch @ vue.runtime.esm.js:6497
Vue._update @ vue.runtime.esm.js:3945
updateComponent @ vue.runtime.esm.js:4066
get @ vue.runtime.esm.js:4479
Watcher @ vue.runtime.esm.js:4468
mountComponent @ vue.runtime.esm.js:4073
push../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
hydrate @ vue.runtime.esm.js:6378
hydrate @ vue.runtime.esm.js:6411

... repeated stack trace here ... then 


**[Vue warn]: Unknown custom element:** <SfHeaderNavigationItem> - did you register the component correctly? For recursive components, make sure to provide the "name" option.


---> <OHeader> at src/themes/capybara/components/organisms/o-header.vue
       <DefaultLayout> at src/themes/capybara/layouts/Default.vue
         <App> at src/themes/capybara/App.vue
           <Root>

...

[Vue warn]: Unknown custom element: <SfHeaderNavigationItem> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
...
[Vue warn]: Unknown custom element: <SfMegaMenuColumn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
...
vue.runtime.esm.js:619 [Vue warn]: Unknown custom element: <SfListItem> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
... etc, etc

```

I checked, and the fix at: https://github.com/DivanteLtd/vsf-capybara/issues/462  has already been applied

Does anyone have any ideas to fix this, please?  Incidentally, I have run into this same exact issue previously when installing to my localhost on MacOS Mojave

## Expected behavior

To display without Errors like at: https://capybara.storefrontcloud.io/

## Steps to reproduce the issue

1. Install core @ [VSF 12.2](https://github.com/DivanteLtd/vue-storefront/tree/v1.12.2) + all services
2. Tested and all was working with default theme
3. Install capybara theme @ [develop branch](https://github.com/DivanteLtd/vsf-capybara/commit/0308d45f53bf05425eac4d199b14b202f5cb479c)
4. Followed instructions at: https://github.com/DivanteLtd/vsf-capybara

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Environment details

- Browser: **Chrome Version 85.0.4183.83 (Official Build) (64-bit)**
- OS: **Digital Ocean Dedicated - 8 GB Memory / 50 GB Disk / NYC1 - Ubuntu 18.04 (LTS) x64 **
- Code Version: 
Core @ [VSF 12.2](https://github.com/DivanteLtd/vue-storefront/tree/v1.12.2) 
Capybara theme @ [develop branch](https://github.com/DivanteLtd/vsf-capybara/commit/0308d45f53bf05425eac4d199b14b202f5cb479c)

<img width="969" alt="Home_Page_-_Vue_Storefront" src="https://user-images.githubusercontent.com/5847833/92293657-60117d80-eee2-11ea-8a43-dcb97f75ed32.png">

**Comment by mrinc** [comment]
I've fixed this.

#528 528 - Is fixed right now by just commenting out the vue-progress-bar.

Currently have the build running and site active with no errors.

Will push up a PR tomorrow for it.

**Comment by lgaitan** [comment]
I was stuck in the same problem.

Follow the instructions in the README.md using submodules and change the branch from master to develop.
It appears that the master branch isn't working

**Comment by krakshayrao** [comment]
The same is happeing with me too. I just installed vuestorefront as it describes in the documentation, and directives like <SfCarouselItem>,<SfBottomNavigationItem>,<SfFooterColumn>,<SfListItem>etc. Tried #528 but did not work. if you know a workaround, pleease help me.

**Comment by mrinc** [comment]
Pull my commit - https://github.com/mrinc/vsf-capybara/commit/1efd2fa0e7cc8b0f9c744b3255de20e1c214bd7f

It has the fixes to get it building.

On another note, if you want this theme for production site - then use the default, this theme is not production ready.

**Comment by krakshayrao** [comment]
> Pull my commit - [mrinc@1efd2fa](https://github.com/mrinc/vsf-capybara/commit/1efd2fa0e7cc8b0f9c744b3255de20e1c214bd7f)
> 
> It has the fixes to get it building.
> 
> On another note, if you want this theme for production site - then use the default, this theme is not production ready.

Pulled the commit, but still the issue persists. Only the carousel is working after updating.

**Comment by mrinc** [comment]
What errors are you getting now?

**Comment by krakshayrao** [comment]
> What errors are you getting now?

SfListItem,SfMegaMenuColumn,SfFooterColumn etc are stillgiving errors. And some error regarding $ attr and $ listners being readonly. 
![image](https://user-images.githubusercontent.com/58678566/98124108-bdbd4880-1ed8-11eb-8999-93cb15f29a3b.png)

**Comment by krakshayrao** [comment]
![image](https://user-images.githubusercontent.com/58678566/98124221-e7766f80-1ed8-11eb-874f-c1db0bdf1ccf.png)
the products are not displaying properly and not responding on click. The navbar also does not pop up modal upon hovering on nav items like Men,Women gears etc. Basically the whole page doesn't respond on button click expect cart, account and home icons in navbar.

**Comment by evgeny-php** [comment]
The same, just installed (v. 1.0.3)
![vsf-errors](https://user-images.githubusercontent.com/74594371/99373126-b9762f80-28c9-11eb-8f36-edddcc873ce9.PNG)

**Comment by evgeny-php** [comment]
And when I install capybara develop:

pm2 stop server
vsf init:theme
? Select theme for Vue Storefront Capybara - based on Storefront UI
? Select theme version In development branch (could be unstable!)
yarn start

or default:
pm2 stop server
vsf init:theme
? Select theme for Vue Storefront Default
? Select theme version Stable version (recommended for production)
yarn start

I gets the same result - theme without content/images and broken functionality
![aaa](https://user-images.githubusercontent.com/74594371/99394527-b2f6b080-28e7-11eb-924c-218e55cd5379.PNG)

**Comment by philem208** [comment]
Hi, i am getting currently the same error...

**Comment by saturn72** [comment]
Same issue on my end as well

What is the latest stable version?

**Comment by GeorgieKirschner** [comment]
Hi, I am also getting these console errors about components not being registered on a fresh install of VSF with Capybara them. Has there been any progress on this issue?

**Comment by saturn72** [comment]
@GeorgieKirschner FYI - moving to non-master branch solve the issue for me

**Comment by philem208** [comment]
I changed also to the development branch and I also installed the theme with vsf theme:init. I do not exactly know why, but the this way worked for me.

**Comment by Fifciu** [comment]
This is fixed by: https://github.com/DivanteLtd/vsf-capybara/pull/463

**Comment by christinewaol** [comment]
I have the same issue here  #1610
https://github.com/vuestorefront/storefront-ui/issues/1610
